name: Setup cache for Deno

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.deno
          ~/.cache/deno
          ~/Library/Caches/deno
          ~/AppData/Local/deno
        key: deno_cache-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('deno.lock') }}
        restore-keys: |
          deno_cache-${{ runner.arch }}-${{ runner.os }}
