name: Cache Deno dependencies
description: Setup and restore cache for Deno dependencies (multiple OS support)

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.deno
          ~/.cache/deno
          ~/Library/Caches/deno
          ~/AppData/Local/deno
        key: deno_cache-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('deno.lock') }}
        restore-keys: |
          deno_cache-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('deno.lock') }}
