name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  action-cache-deno:
    name: Test cache-deno action
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: hasundue/setup-deno@feat-repo-cache
        with:
          deno-version: v1.x
          cache: true

      - name: Setup cache for Deno
        uses: ./.github/actions/cache-deno

      - name: Cache dependencies
        run: deno cache mod.ts
        working-directory: ./.github/actions/cache-deno/test
