name: Integration

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Restore cache
        uses: hasundue/actions/cache-deno@main

      - name: Run tests
        run: deno task test:integration
