name: Integration

on:
  workflow_call:
    inputs:
      task: 
        description: 'The task to run'
        type: string
        default: 'integration'

permissions:
  contents: read

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Restore cache
        uses: hasundue/actions/cache-deno@main

      - name: Cache dependencies
        run: deno task cache

      - name: Run tests
        run: deno task ${{ inputs.task }}
