name: Create PR for release

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        description: 'The name of the package to release'
        required: true
      release-type:
        type: string
        description: 'The type of release to perform'
        default: 'simple'
      include-v-in-tag:
        type: boolean
        description: 'Whether to include a leading "v" in the tag name'
        required: false
        default: false
      versioning-strategy:
        type: string
        description: 'The strategy to use for determining the next version'
        required: false
        default: 'default'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          package-name: ${{ inputs.package-name }}
          release-type: ${{ inputs.release-type }}
          include-v-in-tag: ${{ inputs.include-v-in-tag }}
          versioning-strategy: ${{ inputs.versioning-strategy }}
          bump-minor-pre-major: true
