name: Test

on:
  workflow_call:
    inputs:
      task: 
        description: 'The task to run'
        type: string
        default: 'test'
    secrets:
      CODECOV_TOKEN:
        description: 'A Codecov token'
        required: true

permissions:
  contents: read

jobs:
  check:
    name: Static
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Restore cache
        uses: hasundue/actions/cache-deno@main

      - name: Cache dependencies
        run: deno task cache

      - name: Check format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Type check
        run: deno task check

  unit:
    name: Unit
    needs: check

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Restore cache
        uses: hasundue/actions/cache-deno@main

      - name: Cache dependencies
        run: deno task cache

      - name: Run tests
        run: deno task ${{ inputs.task }} --coverage=./coverage_profile

      - name: Create coverage report
        run: deno coverage ./coverage_profile --lcov --output=./coverage.lcov

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./
          file: ./coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
