name: Update Deno dependencies

on:
  workflow_call:
    inputs:
      head-branch:
        type: string
        description: 'The name of the branch to push the changes to'
        default: 'github-actions/update-deno'
    secrets:
      GH_TOKEN:
        description: 'A GitHub token to push commits and create pull requests'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Restore cache
        uses: hasundue/actions/cache-deno@main

      - name: Cache dependencies
        run: deno task cache

      - name: Run update:commit task
        run: deno task update:commit --summary ../title.txt --report ../body.md

      - name: Check result
        id: result
        uses: andstor/file-existence-action@v3
        with:
          files: ../title.txt, ../body.md
      
      - name: Read title.txt
        id: title
        if: steps.result.outputs.files_exists == 'true'
        uses: juliangruber/read-file-action@v1
        with:
          path: ../title.txt

      - name: Read body.md
        id: body
        if: steps.result.outputs.files_exists == 'true'
        uses: juliangruber/read-file-action@v1
        with:
          path: ../body.md

      - name: Create Pull Request
        if: steps.result.outputs.files_exists == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: ${{ inputs.head-branch }}
          title: ${{ steps.title.outputs.content }}
          body: ${{ steps.body.outputs.content }}
          labels: dependencies
          delete-branch: true
