name: Update Deno dependencies

on:
  workflow_call:
    inputs:
      head-branch:
        type: string
        description: 'The name of the branch to push the changes to'
        default: 'github-actions/update-deno'
    secrets:
      PAT_UPDATE:
        description: 'A GitHub personal access token with workflow permission'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup cache for Deno
        uses: ./.github/actions/cache-deno

      - name: Cache dependencies
        run: deno task cache

      - name: Run Molt
        run: deno task update:commit --summary title.txt --report body.md

      - name: Check result
        id: result
        uses: andstor/file-existence-action@v2
        with:
          files: title.txt, body.md

      - name: Push changes
        if: steps.result.outputs.files_exists == 'true'
        run: git push -f origin HEAD:${{ inputs.head-branch }}

      - name: Create Pull Request
        if: steps.result.outputs.files_exists == 'true'
        run: |
          gh pr create --title "$(cat title.txt)" --body "$(cat body.txt)"
          --head ${{ inputs.head-branch }}
        env:
          GH_TOKEN: ${{ secrets.PAT_UPDATE }}
